### ISSUE TITLE
working example? 

### ISSUE THREAD

**Issue by monurakkaya** [tmalbonph/cordova-plugin-sunmi-inner-printer#10]
Hi I've visited all of issues on this repo and the others but couldn't make it work sunmiv2 + ionic5 

Can you paste here a snippet or sth? 

what i did , 

declare var sunmiInnerPrinter:any;  // before component 

and in my method i can see all available methods for sunmiInnerPrinter but they not throwing any error or doing sth. 

cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-printer 0.8.0 "Printer"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-sunmi-inner-printer 1.1.1 "SunmiInnerPrinter"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"

Ionic:

   Ionic CLI                     : 6.10.1 (/Users/monur/.nvm/versions/node/v12.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.7
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 7 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.15.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/monur/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.1 (/Users/monur/.nvm/versions/node/v12.18.1/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

**Comment by tmalbonph** [comment]
Hi @monurakkaya, I don't have live example to show for the moment as most of the project related to this SUNMI v1 drivers were private and most of it where printing codes inserted into www/js/app.js of the KMRS v1 and v2 - the Karenderia Merchant app.
You can check how I used the from this [https://github.com/tmalbonph/cordova-plugin-sunmi-inner-printer/issues/1](https://github.com/tmalbonph/cordova-plugin-sunmi-inner-printer/issues/1)
