### ISSUE TITLE
print Text with custom font sunmi v2 pro

### ISSUE THREAD

**Issue by KyawNaingThuUcsy** [tmalbonph/cordova-plugin-sunmi-inner-printer#11]
`                  sunmiInnerPrinter.printTextWithFont(" Hello World","Magneto",50);
`
Please help how to print with custom font in sunmi v2 pro.
Thanks .

**Comment by tmalbonph** [comment]
Hi @KyawNaingThuUcsy for this particular device **SUNMI V1/V1s**, I will not recommend you to use any graphics and font selection.
1. You can display 1 logo on top of your receipt
2. Then format your receipt information, delimited by LF and each line should be 32 characters long including the LF.
3. then print these text (let say **the_text**) by calling `sunmiInnerPrinter.printOriginalText(the_text, fn_next, fn_error)`
4. where fn_next is the next method to run after successful printing
5. where fn_error is the error handling method (function) the will handle the printing error
