### ISSUE TITLE
Can i use this in react native?

### ISSUE THREAD

**Issue by Jinentonik** [tmalbonph/cordova-plugin-sunmi-inner-printer#12]
Can i use this in react native?

**Comment by tmalbonph** [comment]
@Jinentonik Have you tried it on react native? I can't tell as I never had a project use case for using it on React.
You can visit the [SUNMI website v1](https://docs.sunmi.com/en/documentation/mobile-products/v1/) or [v1s](https://docs.sunmi.com/en/documentation/mobile-products/v1s/) regarding sample codes for this **SUNMI V1/V1s** devices
