### ISSUE TITLE
SunmiInnerPrinter V1 

### ISSUE THREAD

**Issue by saravanacs** [tmalbonph/cordova-plugin-sunmi-inner-printer#4]
what is the use of printerStatusStartListener(); and what value is return ?

For example, i check hasPrinter() function like,

sunmiInnerPrinter.hasPrinter(function(resolve,reject) {
  if(resolve) {
    alert("Resolve "+resolve)
    return resolve;
  }
  else if(reject) {
    alert("Reject  "+ reject)
    return reject;
  }
})

It return, Resolve 1.
In same way using printerStatusStartListener() function like,

sunmiInnerPrinter.printerStatusStartListener(function(onSuccess, onError) {
  if(onSuccess) {
    alert("STATUS Success  "+ onSuccess)
    return onSuccess;
  }
  else if(onError) {
    alert("STATus Error  "+ onError)
    return onError;
  }
})

But, it return undefined

Please how get printerStatusStartListener() value. Please help me sir. 

Thanks in-advance

**Comment by tmalbonph** [comment]
>> what is the use of printerStatusStartListener(); and what value is return ?

If you are using async / await in your javascript; I think this function was intended to return the status on the `resolve` callback on this function printerStatusStartListener()

see `cordova-plugin-sunmi-inner-printer/src/android/com/sunmi/innerprinter/Printer.java`
	*com.sunmi.innerprinter.Printer.printerStatusStartListener(final CallbackContext):void*

see `cordova-plugin-sunmi-inner-printer/src/android/com/sunmi/innerprinter/PrinterStatusReceiver.java`
	*com.sunmi.innerprinter.PrinterStatusReceiver.onReceive(Context, Intent):void*
