### ISSUE TITLE
Sunmi print barcode

### ISSUE THREAD

**Issue by chen6677** [tmalbonph/cordova-plugin-sunmi-inner-printer#6]
Hi Sir,

I am using version 1.1.0 to print the text is working. but when i print with barcode. it just only can print 1 line. the rest cannot print. include the text at bottom.

the code i am use is like this
sunmiInnerPrinter.printBarCode("1234567890", 8, 162, 2, 2);

also that is not error display

I am using ionic 3

thanks

**Comment by chen6677** [comment]
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';

declare var sunmiInnerPrinter: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

	constructor(public navCtrl: NavController, public navParams: NavParams) {

	}
	
	print() {
		sunmiInnerPrinter.printBarCode("1234567890");
	}

}


this is the code

**Comment by tmalbonph** [comment]
@chen6677 
1)
You should chain your printing codes
2)
The plugin is only good when printing text followed by images. or an image followed by text (E.g. a logo then receipts information)
