### ISSUE TITLE
Sunmi T2 printer

### ISSUE THREAD

**Issue by phidoi247** [tmalbonph/cordova-plugin-sunmi-inner-printer#7]
I using your plugin in ionic 5.
sunmiInnerPrinter.printerSelfChecking() is ok 
but printOriginalText() and printString() is not work. Can you help me to fix this

**Comment by tmalbonph** [comment]
@phidoi247 please post the error here.

**Comment by phidoi247** [comment]
I'm tested on ionic serve
```
declare var sunmiInnerPrinter: any;
@Component
...
printTest() {
    sunmiInnerPrinter.printerInit();
    sunmiInnerPrinter.printString('Test print');
  }
```
It's say sunmiInnerPrinter is not declared.

**Comment by phidoi247** [comment]
But when i build to apk file.
The function printerSelfChecking() work perfect
But function printString() is not work
And i dont know how to view error log in this sunmi t2 device

**Comment by tmalbonph** [comment]
@phidoi247 How you build your APK?
I am asking because how is your app includes
`cordova-plugin-sunmi-inner-printer/www/innerprinter.jswww/innerpriter.js` ?

**Comment by phidoi247** [comment]
> @phidoi247 How you build your APK?
> I am asking because, I want to know how is your app includes this
> `cordova-plugin-sunmi-inner-printer/www/innerpriter.js` ?

cordova plugin add https://github.com/tmalbonph/cordova-plugin-sunmi-inner-printer.git
-> after this i was deleted platform/android
ionic cordova platform add android       
ionic cordova build android

**Comment by tmalbonph** [comment]
@phidoi247 you can look at discussion here
`https://github.com/labibramadhan/cordova-sunmi-inner-printer/issues/14`
And comeback here if you can't still resolve your issue.

**Comment by phidoi247** [comment]
> `https://github.com/labibramadhan/cordova-sunmi-inner-printer/issues/14`

i followed your link. But i cant do the 5th step
Its say: > Could not find method compile() for arguments [com.sunmi:sunmiui:latest.release] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by tmalbonph** [comment]
>> But i cant do the 5th step
You should locate `platforms/android/build.gradle` and edit it as posted

**Comment by natnat1432** [comment]
Hello, I'm using the cordova plugin inside my capacitor project. Is there any way how to fix this? 

This is the error:

Could not find any matches for com.sunmi:sunmiui:latest.release as no versions of com.sunmi:sunmiui are available.
Required by:
    project :capacitor-cordova-android-plugins

**Comment by natikins86** [comment]
Having the same issue, no longer able to build or release updates, not possible to remove this plugin unfortunately, is there anyway to override to build?

Could not find any matches for com.sunmi:sunmiui:latest.release as no versions of com.sunmi:sunmiui are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/sunmi/sunmiui/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/sunmi/sunmiui/maven-metadata.xml

**Comment by fr20587** [comment]
@natikins86 have you solved this? I need help with the same issue

**Comment by carp22** [comment]
@natikins86 Were you able to find a solution? I'm having the same issue. Trying to add Sunmi-inner-print plugin but every time I try to build android it returns:

   > Could not find com.github.AhmedElsayed94:SunmiPrinterSdk:1.0.0.
     Required by:
         project :app
