### ISSUE TITLE
Old data printed

### ISSUE THREAD

**Issue by phidoi247** [tmalbonph/cordova-plugin-sunmi-inner-printer#8]
I'm used `sunmiInnerPrinter.printBitmap` to print my image.
But it printed old data instead of new data.
I tried printing text and images but the results were similar.
For example:
- 1st cmd: printOrginalText('first') -> printer not work
- 2nd cmd: printOrginalText('second') -> print 'first'
- 3rd cmd: printOrginalText('third') -> print 'second'

**Comment by tmalbonph** [comment]
@phidoi247 Are you still having this problem?

**Comment by phidoi247** [comment]
> @phidoi247 Are you still having this problem?

Yes, I am still having this problem
I am using Sunmi T2

**Comment by tmalbonph** [comment]
@phidoi247 Sorry. This repository is applicable only for SUNMI V1 or V2

You can refer to my previous post here: https://github.com/labibramadhan/cordova-sunmi-inner-printer/issues/14
